FROM node:20-alpine

WORKDIR /app

# Copy package.json để install dependency trước
COPY package*.json ./
RUN npm install

# Copy toàn bộ mã nguồn
COPY . .

# Mở port
EXPOSE 3000

# Chạy Next.js ở mode development
CMD ["npm", "run", "dev"]