FROM node:18-alpine

WORKDIR /app

# Copy package.json để install dependency trước
COPY package*.json ./
RUN npm install

# Mở port
EXPOSE 3000

# Chạy Next.js ở mode development
CMD ["npm", "run", "dev"]